language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-google-google_play_services
    - extra-android-m2repository
    - addon-google_apis-google-25
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

jdk:
  - oraclejdk8

notifications:
  email: false

script: ./gradlew assemble check
